### PR TITLE
Cross-team channels

### PR DESCRIPTION
**Pull request by bockets**

### CODE REVIEW

**Review by sogamoso — APPROVED** [review]
I like this idea. Let's give it a try and see how it goes!

**Comment by bockets** [comment]
Hmm i wonder if we need some index of these so that people can easily find the topics when they join BP.

**Comment by RenatoCoelho-BiggerPockets** [comment]
@bockets So we only have a single source of truth, and to ensure we don't have to update something in two places, I propose we migrate the "Our Practices" of the patterns to the "Practices" of our Notion and just leave a link on patterns to the [Practices](https://www.notion.so/biggerpockets/Practices-98492be823df48c0bc897c093a8d6dc8) notion page.
wdyt?

**Comment by bockets** [comment]
> @bockets To ensure we have single source of truth, and so we don't have to update something in two places, I propose we migrate the "Our Practices" of the patterns to the "Practices" of our Notion and just leave a link on patterns to the [Practices](https://www.notion.so/biggerpockets/Practices-98492be823df48c0bc897c093a8d6dc8) notion page.
> wdyt?

@RenatoCoelho-BiggerPockets ya that's been brought up before. It makes sense to me. Lets discuss at next Patterns meeting (Aug 29)

**Comment by baerbradford** [comment]
The distinction in my mind between this repo and what we have in Notion is that patterns here are focused on development practices that can be cited during peer review while Notion is a focus on processes for our department.

What I would expect to see here are styles, conventions, techniques, etc documented that facilitate us having a consistent, maintainable, secure, scalable codebase. Developers don't often agree on these types of things, so keeping it here forces our hand on having a peer review process and regular discussion. This repo is also publicly accessible, so I think it makes little sense to put things specific to our organizational processes here.

This article, to me, is an example of something that should live in Notion. I don't expect somebody to reference this as a pattern we follow when pairing with someone or going through peer review. It simply describes an organizational process we follow to collaborate on projects.

**Comment by RenatoCoelho-BiggerPockets** [comment]
> The distinction in my mind between this repo and what we have in Notion is that patterns here are focused on development practices that can be cited during peer review while Notion is a focus on processes for our department.
> 
> What I would expect to see here are styles, conventions, techniques, etc documented that facilitate us having a consistent, maintainable, secure, scalable codebase. Developers don't often agree on these types of things, so keeping it here forces our hand on having a peer review process and regular discussion. This repo is also publicly accessible, so I think it makes little sense to put things specific to our organizational processes here.
> 
> This article, to me, is an example of something that should live in Notion. I don't expect somebody to reference this as a pattern we follow when pairing with someone or going through peer review. It simply describes an organizational process we follow to collaborate on projects.

@baerbradford I suggest we create a notion page on what goes in what bag (Patters or Notion) according to this description of yours. This not being clear leads to duplication like we have with [Creating good PRs](https://www.notion.so/biggerpockets/Creating-good-PRs-8a2a8faa7b754a459b173bfbdc6dbe6f) (notion) and [Pull Requests](https://biggerpockets.github.io/patterns/practices/creating-a-pr) (patterns), in this case should the patterns one prevail?

**Pull request closed without merging**
