### PR TITLE
Pattern: Test all public interfaces

### PR DESCRIPTION
**Pull request by SpiderMasterMind**

### CODE REVIEW

**Review by sebsogamoso — COMMENTED** [review]
I'm not particularly fond of this one. Allow me to elaborate.

I agree that we should ONLY test public methods, and never private methods directly. But I don't think we need to test ALL public methods.

Some public methods are trivial. Adding a test to those methods don't add any value. Here are some real examples.
- A regular method on any class.
Real example:
```rb
# app/models/social_user.rb

def god?
  id == SocialUser.god_account_id
end
```
- Some public methods like simple ActiveRecord scopes should be treated as trivial methods. 
Real example:
```rb
# app/models/social_user.rb

scope :active, -> { where.not(activated_at: nil) }
```
- Controller actions can also be quite trivial as well.
```rb
# app/controllers/notes_controller.rb

def index
  @notes = current_user.notes.order("created_on DESC")
end
```

That's not to say that aren't methods, ActiveRecord scopes, and controller actions, that should be tested. 

Hard rules like this tend to incentivize the wrong practices. We want tests for the sake of shipping code to production with a certain level of confidence, not for the sake of testing every line of code we write.

To be clear, I'm advocating for shipping untested code. Ideally, the code in the examples I shared above is being tested at a higher level of abstraction, in conjunction with other pieces of code. Testing trivial pieces of code in isolation doesn't really make our test suite more robust or trustworthy.

So what I am saying we should do instead? With the risk of sounding naive, I believe that we should trust each programmer in the team to make the right choices about whether a public method warrants a test or not. Not in terms of "do I feel like writing a test for this method?", but more in the way of "do I feel comfortable leaving this method untested?".

If that fails, we still have code review. Where we can raise concerns of any non-trivial untested code being added to the codebase.

**Comment by SpiderMasterMind** [comment]
@sebsogamoso Thanks for your reply!

(They may be outdated values but) I have subscribed to the `Always be testing` club in https://biggerpockets.github.io/patterns/values.html

Perhaps this pattern could be `MOST` instead of `ALL`?

...

I just think its safer to write a test than not to. If we write a test for something trivial in a few minutes it could prevent us from deleting a class, typoing a method name, getting scopes wrong etc.

I also think it sets a good example for a new class to have a test so subsequent specs are faster to write.

> I believe that we should trust each programmer in the team to make the right choices about whether a public method warrants a test or not

I think this would be great! However I think the notion of `trust` can be too subjective in this case - there's just too many varying factors to affect these sorts of decisions:
- Developer experience
- Codebase knowledge
- Time constraints (pressure to complete tasks, fixing a production affecting bug etc)

Shouldn't we eliminate these factors by just adding some additional tests?

> Ideally, the code in the examples I shared above is being tested at a higher level of abstraction, in conjunction with other pieces of code

For many public interfaces I guess the appropriate higher level of abstraction is an integration test - but we all know how problematic these are. I'd be more aligned with your thinking if there was something better..

**Comment by sebsogamoso** [comment]
> @sebsogamoso Thanks for your reply!

> (They may be outdated values but) I have subscribed to the Always be testing club in https://biggerpockets.github.io/patterns/values.html

> Perhaps this pattern could be MOST instead of ALL?

Thanks for sharing that, I haven't realized we had **Values** here. This makes me wonder, do we really need to have values different from those of BiggerPockets? Do these values really represent those of the current team?

Nonetheless, even if we decide to stick with those values. I think I generally agree that _Always be testing_ sounds like a good idea, but it's up for interpretation though. What stands out to me is "if it’s not tested, how do we know it works?". We can achieve this goal in different ways, automated testing is certainly the most obvious one, but it doesn't necessarily have to be through unit testing every public method, in fact, I don't think that's the most effective way of doing it.

**Comment by SpiderMasterMind** [comment]
@sebsogamoso Yeh I don't know if we should have an engineering values either, maybe something written down about `engineering culture` that we are still trying to figure out 😆 . My mentioning of it was to give some context on my standpoint on this stuff :)

**Comment by SpiderMasterMind** [comment]
Closing following the discussion here, and discussion with others/research. I think we would definitely benefit from a more nuanced description of `when to test`

**Pull request closed without merging**
