### PR TITLE
Use OpenAPI when designing APIs

### PR DESCRIPTION
**Pull request by johngallagher**
## What

Propose using OpenAPI with Design First principles.

## Why

* We're starting to onboard partners such as RentRedi
* We'll be doing a lot more work with partners in the future
* If we agree on these ideas early, it'll save us a lot of pain further down the road

### CODE REVIEW

**Review by RenatoCoelho-BiggerPockets — APPROVED** [review]
The [API Design-First vs Code First](https://apisyouwonthate.com/blog/api-design-first-vs-code-first) was a very interesting read. 

I'm in! Thanks John for getting ahead of the problem.

**Review by bockets — CHANGES_REQUESTED** [review]
Is this really a pattern? Sounds more philosophical. You added OpenAPI to the title, which is a good approach IMO, but then didn't discuss it in the body of the document. I thing reaching for _standards first_ is a great idea and a good way to avoid reinventing the wheel or falling into NIH syndrome.

**Comment by bockets** [comment]
After having seen what it takes to actually implement OpenAPI:

At our scale, I don't think that there is a great reason to adopt it and a few good reasons to avoid it.

We don't have difficulty maintaining our Rails-based API. Contracts are upheld through practice.

The issues we have with OpenAPI, as implemented, are unexpectedly annoying. Custom logging needed was needed. It has problems interacting with some gems. I can see it leading to duplication of logic. The extra documentation OpenAPI provides is nice, but not necessary. And it requires proprietary software to maintain.

Definitely open to making this great for everyone, so let me know your thoughts.

**Review by bockets — APPROVED** [review]
Approving as discussed in Patterns and Practices meeting.

**Comment by baerbradford** [comment]
@johngallagher I think we can close this unless there are some aspects you're wanting to keep.

**Comment by johngallagher** [comment]
Not using OpenAPI for now. Rip it out and merge the code into the main body of the Rails app.

**Pull request closed without merging**
